// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedditPosts.Data;

namespace RedditPosts.Migrations.SubredditInfoMigrations
{
    [DbContext(typeof(SubredditInfoContext))]
    [Migration("20210605021902_IsDead")]
    partial class IsDead
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("RedditPosts.Models.SubredditInfo", b =>
                {
                    b.Property<string>("SubredditName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("TEXT");

                    b.HasKey("SubredditName");

                    b.ToTable("SubredditInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
